version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'inspection-api-postgres'
    environment:
      - 'POSTGRES_DB=inspection'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
